export const BASE_URL = process.env.BASE_URL;
export const DOMAIN = process.env.DOMAIN;
export const clientApi = process.env.BASE_URL + '/client';
export const chatApi = process.env.BASE_URL + '/chat';
export const paymentApi = process.env.BASE_URL + '/client/payment';
export const notificationApi = process.env.BASE_URL + '/notification';

export const  PAYPAL_URL = "https://api-m.sandbox.paypal.com";

export const credentials = `${process.env.REACT_APP_PAYPAL_CLIENTID}:${process.env.REACT_APP_PAYPAL_SECRET_KEY}`;

/* ******* Firebase_________PRODUCTION__START ********/
// export const firebaseOptions = {
//     apiKey: "AIzaSyDkBjYo7RVMXJtPygQcBN0YkL9pzcS3dMQ",
//     authDomain: "skillyahosr.firebaseapp.com",
//     projectId: "skillyahosr",
//     storageBucket: "skillyahosr.appspot.com",
//     messagingSenderId: "821286326684",
//     appId: "1:821286326684:web:92f65a445dc4e364643859",
//     measurementId: "G-PYN8G1PTMD"
// }

// export const firebasePublicKey = 'BNkC6lfOrO0Bcel1gWCeOvqpM80vH-1AxaRmw8RuMvCMW37qtituvsg7SNrhROirnTQB0-LFzlggR7TINYd6cM4';

export const requests = {
    login: BASE_URL + '/auth/login',
    skillerRegister: clientApi + '/teacher',
    seekerRegister: clientApi + '/student',
    getProfile: clientApi + '/user/profile',
    updateSkillerProfile: clientApi + `/teacher/personal`,
    addUpdateTeachingDetails: clientApi + `/teacher/teaching-details`,
    getaddUpdateEducations: clientApi + `/education`,
    updateSeekerProfile: clientApi + `/student`,
    documentPreSigned: clientApi + '/attachment/pre-signed-url',
    documentPostSigned: clientApi + '/attachment',
    experience: clientApi + `/experience`,
    getSubjectCategory: clientApi + `/subject-category`,
    updatePassword: clientApi + `/user/update-password`,
    searchSkiller: clientApi + `/teacher/listing`,
    subjectCategory: clientApi + `/subject-category`,
    getFile: clientApi + `/attachment`,
    certificate: clientApi + `/certificate`,
    clientSubject: clientApi + `/subject/my-subjects`,
    subjects: clientApi + `/subject`,
    contactUS: clientApi + `/contact-us`,
    profileProgress: clientApi + `/teacher/profile-completion`,
    skillerViewProfile: clientApi + `/teacher`,
    skillers: clientApi + `/teacher/listing`,
    availability: clientApi + `/availability`,
    getAvailability: clientApi + `/availability/my-availability`,
    deleteAvailability: clientApi + `/availability`,
    countries: clientApi + `/country`,
    sentMessage: chatApi,
    myMessages: chatApi + `/my-threads`,
    lecture: clientApi + `/lecture`,
    myLectures: clientApi + `/lecture/my-lectures`,
    updateLectureStatus: clientApi + `/lecture/update-status`,
    mySeekers: clientApi + `/teacher/my-seekers`,
    mySkillers: clientApi + `/student/my-skillers`,
    requestSkiller: clientApi + `/seeker-request`,
    allMyRequests: clientApi + `/seeker-request/my-requests`,
    allSeekerRequests: clientApi + `/seeker-request/all-requests`,
    seekerViewProfile: clientApi + `/student`,
    findThread: chatApi + `/find-thread`,
    review: clientApi + `/review`,
    connectStripeAccount: paymentApi + `/connect-account`,
    stripeAccountId: clientApi + `/teacher/findById`,
    createPaymentIntend: paymentApi + `/payment-intent`,
    confirmPayment: paymentApi + `/payment-intent/confirm`,
    refundPayment: paymentApi + `/refund`,
    forgotPassword: clientApi + `/user/forgot-password`,
    updateForgotPassword: clientApi + `/user/update-forgot-password`,
    staticValues: clientApi + `/static-values`,
    transaction: paymentApi + `/transactions`,
    accountBalance: paymentApi + `/connect-account/balance`,
    payoutPayment: paymentApi + `/payout`,
    notification: notificationApi,
    markAllReadNotification: notificationApi + `/mark-all-as-read`,
    markAsReadNotification: notificationApi + `/mark-as-read`,
    withdraws: clientApi + `/withdraw`,
    paymentDocumentPreSigned: paymentApi + '/identity-card/get-presigned-url',
    paymentDocumentPostSigned: paymentApi + '/identity-card/upload',
    userSession: BASE_URL + '/user-session',
    getPaymentFile: paymentApi + '/identity-card',
    upcomingLectures: clientApi + '/lecture/upcoming-lectures',
    emailVerify: clientApi + `/user/email-verify`,
    resendEmailVerification: clientApi + `/user/resend-verification-mail`,
    removeSqsNotification: notificationApi + `/sqs-messages/remove`,
    blogs: clientApi + `/blog`,
    openEdx: clientApi + `/openedx/courses-api`,
    dashboardStripe: paymentApi + `/dashboard-link`,
    highlights: clientApi + `/highlight`,
    socialLogin: BASE_URL + `/auth/login-social`,
    linkedInLogin: BASE_URL + `/auth/linkedIn-social`,
    getMyCourses: BASE_URL + `/myCourses`,
    getAllCourses: BASE_URL + `/course`,
    getSkillerCourses: BASE_URL + `/course/teacher`,
    addCourse: BASE_URL + `/course/add`,
    getCourseLectures: BASE_URL + '/course-lecture',
    addCourseLecture: BASE_URL + `/course-lecture/add`,
    getCourseRating: BASE_URL + `/course-rating`,
    enrollCourse: BASE_URL + `/enroll`,
    addCourseRating: BASE_URL + `/course-rating/add`,
    enrolledStudents: BASE_URL + `/enrolledStudents`,
    coursePaymentIntend: clientApi + `/course-payment/payment-intent`,
    confirmCoursePayment: clientApi + `/course-payment/payment-intent/confirm`,
    getAllSeekerCourses: BASE_URL + `/course/student`,
    paypalPay: clientApi + `/paypal-payment/pay`,
    paypalSuccess: clientApi + `/paypal-payment/success`,
    storePayment: clientApi + `/payment/store`,
    schedulePaypalLecture:  clientApi + `/paypal-payment/schedule-lecture`,
    refundPaypal: clientApi + `/paypal-payment/refund`,
    updatesAnnouncements: clientApi + `/announcement`,
}